[package]
name = "arp-scan"
description = "A minimalistic ARP scan tool"
license = "AGPL-3.0-or-later"
version = "0.15.1"
authors = ["Saluki"]
edition = "2024"
readme = "README.md"
homepage = "https://github.com/kongbytes/arp-scan-rs"
repository = "https://github.com/kongbytes/arp-scan-rs"
keywords = ["arp", "scan", "network", "security"]
categories = ["command-line-utilities"]
exclude = ["/.semaphore", "/data", "/release.sh", ".*"]
rust-version = "1.90"

[dependencies]

# CLI & utilities
clap = { version = "4.5", default-features = false, features = ["std", "suggestions", "color", "help"] }
ansi_term = "0.12"
rand = "0.9"
ctrlc = "3.5"

[target.'cfg(target_os = "linux")'.dependencies]
caps = "0.5.6"

# Network
pnet = "0.35"
pnet_datalink = "0.35"
ipnetwork = "0.20"
dns-lookup = "3.0"

# Parsing & exports
csv = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
